### ISSUE TITLE
This doesn't work

### ISSUE THREAD

**Issue by wackywendell** [johnotander/atom-underline-trailing-whitespace#1]
I installed it into Atom, restarted, opened a file, added some trailing whitespace, saved, and at no time did I see any underline. Something isn't working.

Atom v0.187, underline-trailing-whitespace v1.0.1.

**Comment by johno** [comment]
Thanks for reporting this.

The plugin won't display trailing whitespace on the current line where your cursor is (default behavior for atom). Did you try adding trailing whitespace on another line?

**Comment by wackywendell** [comment]
Ah, good question. I just tried that, and still no underline. Hmm...

**Comment by johno** [comment]
So, I've just been able to verify that it isn't working for me, either. I haven't noticed the lack of functionality because I haven't been using atom for the last couple weeks. I've got it on my list tomorrow to dive in and figure out why this package is no longer working.

**Comment by johno** [comment]
This should now be fixed.
