### ISSUE TITLE
Deprecated selector in `underline-trailing-whitespace/styles/underline-trailing-whitespace.less`

### ISSUE THREAD

**Issue by steveoh** [johnotander/atom-underline-trailing-whitespace#7]
In `underline-trailing-whitespace/styles/underline-trailing-whitespace.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor .trailing-whitespace,
atom-text-editor::shadow .trailing-whitespace` => `atom-text-editor .trailing-whitespace,
atom-text-editor.editor .trailing-whitespace`

* `atom-text-editor .cursor-line .trailing-whitespace,
atom-text-editor::shadow .cursor-line .trailing-whitespace` => `atom-text-editor .cursor-line .trailing-whitespace,
atom-text-editor.editor .cursor-line .trailing-whitespace`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by ghost** [comment]
Any progress on this?

**Comment by krzysztof-sikorski** [comment]
Should be fixed by my pull request (#8).

Also, this package is super simple, the only thing it does is to add a few CSS rules to editor - so if you cannot wait then disable the package and instead copy its CSS rules into your personal stylesheet ("Edit -> Stylesheet" from Atom menu).

**Comment by johno** [comment]
Now fixed and published, thanks @krzysztof-sikorski !
